ani sprites work

diff --git a/poketerm b/poketerm
--- a/poketerm
+++ b/poketerm
@@ -28,8 +28,8 @@ _help() {
     echo "Examples: pts pikachu"
     echo "          pts s:meowstic+female"
     echo "          pts -s s:bulbasaur+m ns:pikachu+f venusaur"
-    echo "          pts -b charizard-mega-x+male s:ho-oh moltres"
-    echo "          pts -a shiny:squirtle"
+    echo "          pts -b charizard-mega-x+male s:ho-oh moltres-galar"
+    echo "          pts -a shiny:squirtle s:charmander"
 }
 
 
@@ -109,7 +109,7 @@ case "$#" in
 
             if [ -z "$sex_str" ]; then
                 sex_str='male'
-                # TODO: fifty fifty random it male/female
+                # TODO: use the pokemon's gender ratio random it
             fi
 
             if [ $sex_str = 'male' ] || [ $sex_str = 'm' ]; then
@@ -154,11 +154,25 @@ case "$#" in
                 curl -sL \
                     "https://raw.githubusercontent.com/msikma/pokesprite/master/pokemon-gen8/$_type/$sex/$pokemon.png" \
                     -o "$pokemon_desc.png"
+                pokemon_image="$pokemon_desc.png"
 
             elif [ $use_ani == 1 ]; then
+                # default type of ani sprites is "normal"
+                if [ $_type = 'not-shiny' ]; then
+                    _type=normal
+                fi
+
+                # search and replace mega-{x/y} to just mega{x/y} for ani
+                # sprites
+                pokemon=${pokemon/mega-/mega}
+
+                # TODO: for gen 8 prepend "swsh-" to $_type
+
                 curl -sL \
                     "https://projectpokemon.org/images/$_type-sprite/$pokemon.gif" \
                     -o "$pokemon_desc.gif"
+                pokemon_image="$pokemon_desc.gif"
+
             else
                 # default type of big sprites is "default"
                 if [ $_type = 'not-shiny' ] && [ $sex != 'female' ]; then
@@ -186,12 +200,9 @@ case "$#" in
                     url=$(curl -s "https://pokeapi.co/api/v2/pokemon/$pokemon" | \
                         jq -r $json_field)
                 fi
-
                 curl -sL $url -o "$pokemon_desc.png"
-
+                pokemon_image="$pokemon_desc.png"
             fi
-
-            pokemon_image="$pokemon_desc.png"
             pokemon_images+=(${pokemon_image})
         done
         ;;
@@ -222,5 +233,79 @@ if [ $use_ani == 0 ]; then
     done
     rm -f t.png
 else
-    echo "ani!"
+    _width=0
+    min_frame=100
+
+    for _i in "${pokemon_images[@]}"; do
+        # Flip to level the base of each gif
+        convert -flip "$_i" "$_i"
+
+        # Get size
+        _width=$(convert "${_i}[0]" -ping -format "%w" info:)
+        _height=$(convert "${_i}[0]" -ping -format "%h" info:)
+
+        _sum_width=$((_sum_width + _width))
+        sum_widths+=("${_sum_width}")
+        (( _height > max_height )) && max_height=${_height}
+
+        _frame=$(identify "$_i" | wc -l)
+        frames+=("${_frame}")
+        (( _frame < min_frame )) && min_frame=${_frame}
+    done
+
+    specified_frame=$min_frame
+    coalesce_str="convert ${pokemon_images[0]}"
+
+    for _loop_num in "${!pokemon_images[@]}"; do
+        _frame=${frames[$_loop_num]}
+
+        if [ "$_frame" -gt "$specified_frame" ]; then
+            # Delete extra frames from gif
+            extra_frames=$(( _frame - specified_frame ))
+            extra_idx_del_str=""
+
+            for (( _extra_num=0; _extra_num<extra_frames; _extra_num++ )); do
+                idx=$(( _extra_num * _frame / extra_frames ))
+                extra_idx_del_str="$extra_idx_del_str$idx,"
+            done
+
+            convert "${pokemon_images[_loop_num]}" -delete "$extra_idx_del_str" "${pokemon_images[_loop_num]}"
+        else
+            # Insert extra frames into gif
+            extra_frames=$(( specified_frame - _frame ))
+
+            for (( _extra_num=0; _extra_num<extra_frames; _extra_num++ )); do
+                idx=$(( _extra_num * _frame / extra_frames + _extra_num ))
+                convert "${pokemon_images[_loop_num]}" "${pokemon_images[_loop_num]}[$idx]" -insert $idx "${pokemon_images[_loop_num]}"
+            done
+        fi
+
+        if [[ ${_loop_num} -gt 0 ]]; then
+            coalesce_str="${coalesce_str} \
+                -repage ${sum_widths[-1]}x${max_height} -coalesce \
+                null: \( ${pokemon_images[_loop_num]} -coalesce \) \
+                -geometry +${sum_widths[$((_loop_num - 1))]}+0 \
+                -layers Composite\
+            "
+        fi
+    done
+
+    coalesce_str="${coalesce_str} t.gif"
+    eval "$coalesce_str"
+
+    # Flip image back
+    convert -flip t.gif t.gif
+
+    # Cleanup
+    for _i in "${pokemon_images[@]}"; do
+        rm -f "${_i}"
+    done
+
+    trap ctrl_c INT
+    function  ctrl_c() {
+        rm -f t.gif
+    }
+
+    # Display
+    timg --upscale t.gif
 fi
